version: '3.8'

services:
  db:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: moty
      POSTGRES_USER: moty
      POSTGRES_PASSWORD: password
  testdb:
    image: postgres:15.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: moty_test
      POSTGRES_USER: moty
      POSTGRES_PASSWORD: password
