version: '3.8'

services:
  db:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: moty
      POSTGRES_USER: moty
      POSTGRES_PASSWORD: password
    volumes:
      - ./test/initdb.sh:/docker-entrypoint-initdb.d/create-db-user.sh
