name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Test
    services:
      postgres:
        image: postgres:15.0
        env:
          POSTGRES_DB: moty_test
          POSTGRES_USER: moty
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit -- --run
